### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by tomasisainmdom** [iucn-applications/org.iucn.event-rsvp-reminders#1]
I'm looking for this very functionality, but see that it hasn't had any activity in 2 years.  Just wondering if this is still an active project, or if it's moved, or whether it's advisable to attempt to install.

**Comment by iucn-applications** [comment]
Hi @tomasisainmdom 

No, it is no longer an active project. 

We developed this functionality in-house, used it successfully and decided to publish it as an extension, but then business changed and we no longer use it so it hasn't been improved since.

If you want it to use I believe you might be able to with a few adjustments. I'm happy to guide you through what has been done, how to use it and some of the limitations. 

Let me know.

**Comment by tomasisainmdom** [comment]
Thank you for both your response and offer to guide me through what has been done.  I'm not sure I have the technical knowledge to take it on, but I may engage someone to assist as I'd love to get this implemented. Any suggestions or guidance you can provide would be greatly appreciated.

**Comment by iucn-applications** [comment]
I would suggest you start by downloading and installing the extension and test it out to see if it's working. If not, any error messages or specific functionality missing might be a good starting point to making it work.

**Comment by tomasisainmdom** [comment]
I attempted an install, but didn't get very far.  I uploaded and expanded zip in ext directory, refreshed extension manager.  Event RSVP Reminder shows up.  I hit install and get an immediate critical error: 

"Parse error in extension org.iucn.event-rsvp-reminders: Failed to parse info XML: File /home/DOMAIN/www/www/wp-content/uploads/civicrm/ext/org.iucn.event-rsvp-reminders/info.xml does not exist."

**Comment by iucn-applications** [comment]
At first sight it seems like a permissions issue as the file info.xml is present - https://github.com/iucn-applications/org.iucn.event-rsvp-reminders/blob/main/info.xml

I tried to install on the civibuild WP demo installation and managed to install after fixing some inheritance issues on the file CRM/EventRsvpReminders/.php .
Here's the changes I've made: [RSVPActionMapping.txt](https://github.com/iucn-applications/org.iucn.event-rsvp-reminders/files/13975199/RSVPActionMapping.txt)
If you get fatal error when installing like "cannot call static method etc" try replacing the RSVPActionMapping.php with this updated file (rename the extension to php, as I cannot post php files here).

The reason I don't commit this file to the repository is because it doesn't work on my drupal installation, possibly because I'm on an older version. 

I hope this helps.

**Comment by tomasisainmdom** [comment]
Thanks so much!  I really appreciate the assistance.  That file update did allow the extension to be installed without error.  However, none of the tokens seem to be available, and any attempt to enter Scheduled Reminder now throws a critical error.  I checked the log, and the following was logged at the time of the attempt (unsure if it's related):

---------------------------

2024-01-18 09:59:06-0500  [warning] ManagedEntity update policy "unmodified" specified for entity type Job which is not an APIv4 ManagedEntity. Falling back to policy "always".

2024-01-18 09:59:47-0500  [error] (mjwshared) Unable to save managed entity "cg_extend_objects:FinancialTrxn": Value already exists in the database
Array
(
    [exception] => CRM_Core_Exception: "Value already exists in the database"
#0 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/OptionValue.php(34): CRM_Core_BAO_OptionValue::add((Array:9))
#1 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php(171): CRM_Core_BAO_OptionValue::create((Array:9))
#2 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php(140): Civi\Api4\Generic\DAOSaveAction->write((Array:1))
#3 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/DAOSaveAction.php(38): Civi\Api4\Generic\DAOSaveAction->writeObjects((Array:1))
#4 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/Civi/Api4/Provider/ActionObjectProvider.php(72): Civi\Api4\Generic\DAOSaveAction->_run(Object(Civi\Api4\Generic\Result))
#5 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(156): Civi\Api4\Provider\ActionObjectProvider->invoke(Object(Civi\Api4\Generic\DAOSaveAction))
#6 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/AbstractAction.php(256): Civi\API\Kernel->runRequest(Object(Civi\Api4\Generic\DAOSaveAction))
#7 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/api/api.php(91): Civi\Api4\Generic\AbstractAction->execute()
#8 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(223): civicrm_api4("OptionValue", "save", (Array:3))
#9 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(183): CRM_Core_ManagedEntities->insertNewEntity((Array:7))
#10 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(115): CRM_Core_ManagedEntities->reconcileEntities((Array:143))
#11 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(420): CRM_Core_ManagedEntities->reconcile()
#12 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager.php(439): CRM_Core_Invoke::rebuildMenuAndCaches(TRUE)
#13 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php(197): CRM_Extension_Manager->disable((Array:1))
#14 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(622): CRM_Admin_Form_Extensions->postProcess()
#15 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(144): CRM_Core_Form->mainProcess()
#16 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(43): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#17 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#18 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#19 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle("next")
#20 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(364): CRM_Core_Controller->run()
#21 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(170): CRM_Core_Page_Basic->edit(64, NULL)
#22 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php(110): CRM_Core_Page_Basic->run()
#23 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(322): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#24 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:19))
#25 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:3))
#26 /home/DOMAIN/www/www/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke((Array:3))
#27 /home/DOMAIN/www/www/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke("")
#28 /home/DOMAIN/www/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters("", (Array:1))
#29 /home/DOMAIN/www/www/wp-includes/plugin.php(517): WP_Hook->do_action((Array:1))
#30 /home/DOMAIN/www/www/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#31 {main}

)

**Comment by iucn-applications** [comment]
I'm not sure if it's related with the error you're viewing but I got the tokens to appear on the event schedule reminder by modifying the same file one more: 
[RSVPActionMapping.txt](https://github.com/iucn-applications/org.iucn.event-rsvp-reminders/files/13980143/RSVPActionMapping.txt)
Can you please update that file and try again?

**Comment by tomasisainmdom** [comment]
Success! I updated the file as instructed and was able to create an invitation RSVP using tokens via scheduled reminder in the event.  It sent the reminder with the correct URLs, which updated the custom field with response and date.  A few questions:

- Am I correct in assuming the response is not intended to update the Participant Status?  Only the custom field 'response'?
- Is the only reason for the 'Response URL' token (as opposed to simply 'Response'), to provide a raw URL which I can customize, or is there some other differentiation?
- How would I go about customizing the response page?

Thanks again for all your help.  Above and beyond, and greatly appreciated!

**Comment by iucn-applications** [comment]
That's great news! Happy to hear it.

As for your questions:

* Yes, exactly: it's supposed to be merely a declaration of intention, not a commitment to participate
* Exactly. You can use the URL if you want to use a fancy button instead of just a link.
* You can customize the thank you page by changing this file - https://github.com/iucn-applications/org.iucn.event-rsvp-reminders/blob/main/templates/CRM/EventRsvpReminders/Page/RSVPPage.tpl . By default you only have variables $error (true if an error occurred) and $admin_email available (admin email will be one of the emails defined in the Event Location tab if any). In case you need more variables (participant information, etc) you'll need to update the file https://github.com/iucn-applications/org.iucn.event-rsvp-reminders/blob/main/CRM/EventRsvpReminders/Page/RSVPPage.php to define and assign the variables you need. A head's up: this might be a bit technical.

Good luck!

**Comment by tomasisainmdom** [comment]
That's great.  Again, I greatly appreciate your efforts to create this and assistance in helping me get it up and running.  It will be very useful for my needs.

**Comment by iucn-applications** [comment]
Happy to know that this is useful for more people. :)
